/**
 * PS/2 keyboard receiver + scancode translator for the Basys3 USB-HID port.
 *
 * The Basys3 presents a USB HID keyboard to the FPGA as a PS/2 device
 * (ps2_clk ~10-16 kHz, generated by the on-board host).  This module samples
 * 11-bit PS/2 frames on the falling edge of ps2_clk, tracks the E0 (extended)
 * and F0 (release) prefixes, and produces the Nand2Tetris "Keyboard" code of
 * the key currently held down (0 when nothing is pressed).
 *
 * Supported: letters a-z (lowercase ASCII), digits 0-9, space, enter,
 * backspace, esc, and the four arrow keys (Hack codes 130-133) used by Tetris.
 */
module ps2_keyboard(
    input             clk,       // 100 MHz system clock
    input             rst,
    input             ps2_clk,   // async PS/2 clock from keyboard
    input             ps2_data,  // async PS/2 data from keyboard
    output reg [15:0] key_code   // current Hack key code (0 = none)
);
    // ---- synchronize async PS/2 inputs ----
    reg [2:0] clk_s = 3'b111;
    reg [1:0] dat_s = 2'b11;
    always @(posedge clk) begin
        clk_s <= {clk_s[1:0], ps2_clk};
        dat_s <= {dat_s[0],   ps2_data};
    end
    wire clk_falling = (clk_s[2:1] == 2'b10);
    wire data_bit    = dat_s[1];

    // ---- 11-bit frame shift register ----
    // Frame bits arrive LSB-of-frame-first: start, data0..data7, parity, stop.
    // Shifting new bits into the MSB, after 11 shifts frame[8:1] is the data byte.
    reg [10:0] frame  = 11'd0;
    reg [3:0]  bitcnt = 4'd0;
    reg        byte_valid = 1'b0;
    wire [7:0] scancode = frame[8:1];

    always @(posedge clk) begin
        byte_valid <= 1'b0;
        if (rst) begin
            bitcnt <= 4'd0;
            frame  <= 11'd0;
        end else if (clk_falling) begin
            frame <= {data_bit, frame[10:1]};   // shift right, new bit at MSB
            if (bitcnt == 4'd10) begin
                bitcnt     <= 4'd0;
                byte_valid <= 1'b1;             // full frame available next cycle
            end else begin
                bitcnt <= bitcnt + 4'd1;
            end
        end
    end

    // ---- prefix tracking + key state ----
    reg extended = 1'b0;
    reg release_f = 1'b0;

    // translate a (extended, scancode) pair to a Hack key code (0 if unknown)
    function [15:0] translate(input ext, input [7:0] sc);
        begin
            if (ext) begin
                case (sc)
                    8'h6B: translate = 16'd130; // left
                    8'h75: translate = 16'd131; // up
                    8'h74: translate = 16'd132; // right
                    8'h72: translate = 16'd133; // down
                    default: translate = 16'd0;
                endcase
            end else begin
                case (sc)
                    // letters -> lowercase ASCII
                    8'h1C: translate = 16'd97;  // a
                    8'h32: translate = 16'd98;  // b
                    8'h21: translate = 16'd99;  // c
                    8'h23: translate = 16'd100; // d
                    8'h24: translate = 16'd101; // e
                    8'h2B: translate = 16'd102; // f
                    8'h34: translate = 16'd103; // g
                    8'h33: translate = 16'd104; // h
                    8'h43: translate = 16'd105; // i
                    8'h3B: translate = 16'd106; // j
                    8'h42: translate = 16'd107; // k
                    8'h4B: translate = 16'd108; // l
                    8'h3A: translate = 16'd109; // m
                    8'h31: translate = 16'd110; // n
                    8'h44: translate = 16'd111; // o
                    8'h4D: translate = 16'd112; // p
                    8'h15: translate = 16'd113; // q
                    8'h2D: translate = 16'd114; // r
                    8'h1B: translate = 16'd115; // s
                    8'h2C: translate = 16'd116; // t
                    8'h3C: translate = 16'd117; // u
                    8'h2A: translate = 16'd118; // v
                    8'h1D: translate = 16'd119; // w
                    8'h22: translate = 16'd120; // x
                    8'h35: translate = 16'd121; // y
                    8'h1A: translate = 16'd122; // z
                    // digits
                    8'h45: translate = 16'd48;  // 0
                    8'h16: translate = 16'd49;  // 1
                    8'h1E: translate = 16'd50;  // 2
                    8'h26: translate = 16'd51;  // 3
                    8'h25: translate = 16'd52;  // 4
                    8'h2E: translate = 16'd53;  // 5
                    8'h36: translate = 16'd54;  // 6
                    8'h3D: translate = 16'd55;  // 7
                    8'h3E: translate = 16'd56;  // 8
                    8'h46: translate = 16'd57;  // 9
                    // specials
                    8'h29: translate = 16'd32;  // space
                    8'h5A: translate = 16'd128; // enter (newline)
                    8'h66: translate = 16'd129; // backspace
                    8'h76: translate = 16'd140; // esc
                    default: translate = 16'd0;
                endcase
            end
        end
    endfunction

    always @(posedge clk) begin
        if (rst) begin
            extended  <= 1'b0;
            release_f <= 1'b0;
            key_code  <= 16'd0;
        end else if (byte_valid) begin
            case (scancode)
                8'hE0: extended  <= 1'b1;   // extended-key prefix
                8'hF0: release_f <= 1'b1;   // key-release prefix
                default: begin
                    if (release_f) begin
                        // key released -> clear current key
                        key_code <= 16'd0;
                    end else begin
                        key_code <= translate(extended, scancode);
                    end
                    extended  <= 1'b0;
                    release_f <= 1'b0;
                end
            endcase
        end
    end

endmodule
